//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria_Noah.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class comanda
    {
        public int numCda { get; set; }
        public Nullable<System.DateTime> horaCda { get; set; }
        public int qntIng { get; set; }
        public bool massaFeta { get; set; }
        public int qntIngPosats { get; set; }
        public Nullable<System.DateTime> horaFinal { get; set; }
    }
}
