//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria_Noah.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class comanda
    {
        public int numCda { get; set; }
        public Nullable<System.DateTime> horaCda { get; set; }
        public int qntIng { get; set; }
        public bool massaFeta { get; set; }
        public int qntIngPosats { get; set; }
        public Nullable<System.DateTime> horaFinal { get; set; }
    }
}
